### PR TITLE
Set required_ruby_version in gemspec

### PR DESCRIPTION
**Pull request by jeremyevans**
I've confirmed that faye-websocket does not work on ruby 1.8.7.
It may work on ruby 1.9.2, but if you are only testing on ruby
1.9.3+, it's probably best to use that.

### CODE REVIEW

**Comment by jcoglan** [comment]
Have you found out why it doesn't work on ruby 1.8.7?

**Comment by jeremyevans** [comment]
I was originally trying to use this with Roda, which supports 1.8.7, and ended up with the following failure on Travis: https://travis-ci.org/jeremyevans/roda/jobs/64349020.  Here's the important part:

```
  1) Error:
websockets plugin#test_0001_supports websocket requests:
NoMethodError: undefined method `>=' for nil:NilClass
    /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:99:in `emit_error'
    /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/faye-websocket-0.9.2/lib/faye/websocket/client.rb:56:in `initialize'
    ./spec/plugin/websockets_spec.rb:58:in `new'
    ./spec/plugin/websockets_spec.rb:58:in `test_0001_supports websocket requests'
```

So it's erroring out before `@ready_state` is set.  I was able to determine it is because `[*options[:extensions]]` is `[]` on ruby 1.9+, but `[nil]` on 1.8.7, so it is calling `@driver.add_extension(nil)`, which was raising an error.

If you plan on supporting 1.8.7, I can certainly try to get the tests passing on it, but I figured since you weren't testing on it, you didn't want to support it.

**Comment by jcoglan** [comment]
My experience of trying it out just now is that this module works fine on 1.8, but websocket-driver requires 1.9. So if anything the flag belongs on that module.

Still, I'm very cautious about using this rubygems feature. My experience of using the similar feature in Bundler is that it makes fixing compatibility problems harder. With your gem dependencies, rubygems/bundler can actually install the ones you've asked for, whereas neither has any idea how to install Ruby. All they can do if you're running the wrong version is tell you about it, or refuse to install the gems you asked for. In this event, you can't even try to get things working because you can't install the gems to even find out what the problem is.

It also makes `git-bisect` hard to use. If you're trying to find where a ruby-1.8-related bug was introduced, and your gemspec says it needs some other version of Ruby, you have to keep editing the gemspec on each checkout to make rubygems/bundler let you run the code.

Unfortunately, both things that Bundler does in response to this are wrong. If you install a gem using `path` and its required Ruby is not present, nothing happens. If you install it from a remote source, Bundler refuses to install it. What it ought to do is print a warning in both cases, so you at least know there's a potential problem but you can actually install the code and find out. Maybe you're not invoking the code path that requires 1.9? Maybe the devs aren't testing on that version but it happens to work? (I still try to write 1.8-compatible code most of the time and most of the reasons websocket-driver requires 1.9 is because of the `String` API changes.)

My hunch is that websocket-driver could be made to work in 1.8, but nobody has yet complained since I dropped support for it.

**Comment by jeremyevans** [comment]
Fair enough.  I agree this isn't a black-or-white issue, it's more a matter of preference.  Few people are still using ruby 1.8.7 these days, so it doesn't really matter.

I do think there are some 1.8.7 issues in faye-websocket itself.  As I mentioned in the earlier comment, I think https://github.com/faye/faye-websocket-ruby/blob/master/lib/faye/websocket/api.rb#L28 is broken on ruby 1.8 if you don't specify `:extensions`,

**Comment by jcoglan** [comment]
In light of my above comments I'm going to close this; although I'm still somewhat on the fence. I might reconsider it before the next release, depending on how hard it would be to make things 1.8-compatible.
